name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t express-app ./app

      - name: Deploy Docker container
        run: |
          docker stop express-app || true
          docker rm express-app || true
          docker run -d -p 3000:3000 --name express-app express-app
